### PR TITLE
Copter: fix RTL altitude when min_climb is set

### PR DESCRIPTION
**Pull request by jschall**

### CODE REVIEW

**Comment by jschall** [comment]
fixes https://3drsolo.atlassian.net/browse/FC-238

**Comment by rmackay9** [comment]
Ah damn.  Sorry for making this mistake and thanks for finding/fixing it.  The patch looks good.

solo-master and master have diverged so much that porting the fix to master is difficult so I've commited a slightly variation to master.  This difference is ok as long as we don't try to make more changes to the RTL code on top of this one.
https://github.com/diydrones/ardupilot/commit/a18f71b29e85a820819afa385b1e4cede7b5f880

Really we need to get solo-master and ardupilot-master back together.

**Comment by rmackay9** [comment]
I guess we can close this now?

**Comment by jschall** [comment]
This is in.

**Pull request closed without merging**
