### PR TITLE
Final compass calibrator

### PR DESCRIPTION
**Pull request by bugobliterator**
Pull request started with changes such as more info on compass calibrator functions, reorganise calibrator and move math functions out of AP_Compass into AP_Math.
New inverse function which is generic for matrices with dimension > 4.

### CODE REVIEW

**Comment by priseborough** [comment]
Make sure we include compass cals as part of testing

**Comment by jschall** [comment]
Reviewed. See commit comments.

**Comment by jschall** [comment]
Pushed some proposed changes. The comment update is incomplete, pending an explanation of the sample acceptance algorithm by Sid.

**Comment by jschall** [comment]
Merged to solo-U1.1 branch.

**Pull request closed without merging**
