### PR TITLE
GPS_ACCURACY mavlink message

### PR DESCRIPTION
**Pull request by tcauchois**
Full of useful GPS debugging info, for consumption by ground control.

### CODE REVIEW

**Comment by tcauchois** [comment]
@jschall or anybody else, want to look at this?

**Comment by Gussy** [comment]
Nice!

Can you also make a PR to https://github.com/3drobotics/mavlink-solo with the mavlink message changes? That's the master for these XML files :+1:

**Comment by jschall** [comment]
@tcauchois What is this for? Is it just for debugging purposes? We could use something like NAMED_VALUE_FLOAT for that.

**Comment by tcauchois** [comment]
@jschall this is so we can display things like GPS drift on a ground control station, for tuning GPS limits.  I'd talked to a bunch of people about it and there was some consensus this was a generally useful message.  I'm not tied to particular design decisions as much as I just need these values sent back, and this code is already written.

**Comment by jschall** [comment]
I think that NAMED_VALUE_FLOAT should be more than sufficient for temporary GPS debugging purposes.

**Comment by jschall** [comment]
Discussed with Alan - sounds like this is needed for an in-app display. If so, happy to merge it, but it needs to contain all the information necessary to synthesize the in-app display (e.g., if you want a boolean display that shows whether the thresholds have been crossed, you should include either those boolean values or the threshold values needed to calculate them)

**Comment by tcauchois** [comment]
https://github.com/3drobotics/ardupilot-solo/pull/168 rewritten here.

**Comment by tcauchois** [comment]
Closed in favor of https://github.com/3drobotics/ardupilot-solo/pull/169

**Pull request closed without merging**
