### PR TITLE
make: update oreoled firmware to v1.4

### PR DESCRIPTION
**Pull request by Gussy**
Updates the new oreoled firmware to v1.4, which changes some of the in-built RGB colour mixes.

### CODE REVIEW

**Comment by jschall** [comment]
merged

**Comment by rmackay9** [comment]
this is an easy one to get into master I think..

**Comment by jschall** [comment]
Pretty sure you don't want to waste flash on oreoled firmware on upstream

**Comment by rmackay9** [comment]
I think we already do though, it's already in there it's just now a bit out of date.

**Pull request closed without merging**
