### PR TITLE
Improve in-flight reset of earth frame magnetic field states - JIRA SOLO-564

### PR DESCRIPTION
**Pull request by priseborough**
High rotation rates could cause the sampling of the magnetometer to be incorrectly rotated into earth frame coordinates when performing an in-flight reset of the magnetic field states. This addresses the following JIRA issue.

https://3drsolo.atlassian.net/browse/SOLO-564

### CODE REVIEW

**Comment by jschall** [comment]
If possible I think we should include an up-to-date answer to this question with every new PR: what level of testing has this PR been subjected to by the author?

**Comment by jschall** [comment]
Reviewed. I don't like quaternion division because quaternion multiplication is not commutative - it is not clear whether the quaternion on the LHS or RHS is inverted.

**Comment by priseborough** [comment]
These patches have been flight tested on upstream and were cherry picked into solo with minor conflicts.

**Comment by jschall** [comment]
Great, thanks!

**Pull request merged**
