### PR TITLE
Dataflash mavlink

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by jschall** [comment]
@bugobliterator @peterbarker the time is right! Lets do it! Is the sololink side done?

**Comment by peterbarker** [comment]
I'm trying to work out why I'm getting +8% CPU usage on telem_forwarder ATM.  The dataflash_logger - which also does the whole mavlink_parse_char thing - sits at 2% total consistently.

There's also one other problem I need to sort out - due, I believe to recent changes to telem_forwarder to implement basic mavlink routing (this stops us sending the dataflash-mavlink packets to mavproxy; you can imagine why.

Soon.

**Comment by peterbarker** [comment]
The increased CPU usage seems to be directly related to the amount of data being read from the serial port by telem_forwarder.   The extra time all appears to be system time - so it's the act of reading from the serial port, and forwarding the extra traffic onto dataflash_logger itself causing the CPU usage.

I think this extra CPU usage is ours to keep.

**Comment by jschall** [comment]
As discussed on mumble:
- Needs to run in parallel with SD card logging, because we need to guarantee the ability to prove that any crashes were not caused by mavlink logging
- Needs a parameter to set logging mode - SD card only, mavlink only or both

**Comment by peterbarker** [comment]
We now have a parameter LOG_BACKEND_TYPE - 0 for no backend, 1 for file, 2 for mavlink, 3 for both.

**Comment by jschall** [comment]
Is this history so long because it preserves history from upstream? It is not very review-able as-is.

Does not cleanly rebase on master at the moment because I merged your other PR.

**Comment by jschall** [comment]
Also for project salmon purposes I'd like it to be made clear what parts of this are already in upstream and what parts are not, or ideally it'd all be in upstream already.

**Comment by peterbarker** [comment]
I was preserving some of other people's patches, and some work which is only required for DataFlash_MAVLink rather than being specifically for DataFlash_MAVLink (the frontend/backend split, for example).

Looking at the final delta is probably the best way to review.

I can fold into fewer patches if you want.

**Comment by peterbarker** [comment]
Upstream already include the frontend/backend split and the ability to trickle messages out to logs.

However, upstream and ardupilot-solo have diverged enough to make moving deltas between the two is difficult - one notable change being the different functor implementation being used upstream.  I was initially doing things upstream and moving them to solo afterwards - but as the two diverged I made the decision to work solely on the Solo branch for dataflash-mavlink and get things upstream after it was in Solo.

**Comment by jschall** [comment]
Is it possible to reset our dataflash library to upstream's and then add whatever changes are needed? We need to do things in a way that allows us to move to a branch based on upstream without regressions.

**Comment by jschall** [comment]
If we've diverged too much for that we'll have to settle for a very clear understanding of the feature diff between solo and upstream.

**Comment by jschall** [comment]
merged!

**Pull request closed without merging**
