### PR TITLE
Save configuration to non-volatile memory in UBlox GPS

### PR DESCRIPTION
**Pull request by bugobliterator**
There is an availability in ublox-7n to store configuration inside onboard flash and BBR RAM if commanded to do so. This PR/commit makes ubx GPS driver to use this feature after any change that is made to config.

### CODE REVIEW

**Comment by jeevan** [comment]
Cool - what is the benefit of this change?

**Comment by bugobliterator** [comment]
@jeevan currently GPS driver doesn’t check the acknowledgements to sent messages coming from GPS module, so it makes GPS vulnerable to not get all the configuration settings(although such an instance hasn't been found). This patch is an innocuous change compared to making GPS driver acknowledge every message it sends.

**Comment by bbasso** [comment]
Hey @jschall , I thought we were not including this in U0.1 meeting minutes below - was there a change?

https://docs.google.com/document/d/1JvV1Q-mPYqiThLAdLNm0qgFoDRXAGp_aA-YL2jlNUQ0/edit

**Comment by jschall** [comment]
@bbasso We're doing testing and slowly gaining confidence that this fixes one of the long TTFF issues.

**Comment by jschall** [comment]
So far we've reproduced the issue twice with normal firmware and done a lot of tests with no reproduction on this patch.

**Comment by jschall** [comment]
Based on a mean attempts to reproduce of 10 (per Sid's estimate), we're about 93.75% confident that this fixes that issue. All it takes is one failure to debunk that, though.

**Comment by jschall** [comment]
And we've reverted this twice and been able to reproduce again during our testing.

**Comment by bugobliterator** [comment]
I thought we agreed that it was included. Maybe we just forgot to struck that as yes on the doc.

**Comment by bbasso** [comment]
Could be--happy to include if it's solving a present issue with GPS !

**Comment by bugobliterator** [comment]
yes it does, so far :laughing:

**Comment by jschall** [comment]
Reviewed.

**Comment by jschall** [comment]
merged for U0.1

**Pull request closed without merging**
