### PR TITLE
Make 4th Mavlink port work and to be used as accessory bay telemetry

### PR DESCRIPTION
**Pull request by bugobliterator**

### CODE REVIEW

**Comment by rmackay9** [comment]
stop the porting, let's all get on master!

**Comment by bugobliterator** [comment]
This point has been discussed a lot of times, and I think there was a consensus in doing it piece wise, ie make PRs of the big changes from master to solo and vice-versa. Many of the changes are too big to be rebased in one go, so if we keep exchanging PRs of such changes and deal with them separately we might be able to get close enough at some point to do full rebase.

**Comment by bugobliterator** [comment]
First step is to get mag cal and probably accel cal PRed to master
Mag cal pr is ready to go, and will be PRed to master shortly.

from master to solo, first step would be transition to cpp from pde files. If we are luck these changes will make rebasing way easier than the current state.

**Comment by jschall** [comment]
Breaks gimbal somehow. Reverted. Needs work.

**Comment by sondree** [comment]
Enabling output on serial 2 via shell also breaks gimbal. Working theory is that Serial 2 is somehow connected to the gimbal pitch control.

**Comment by peterbarker** [comment]
njoubert collected together information on how things are connected in Solo.  I've reorganised this and have it about ready to be pulled into solodevguide.

This information is in tables here: https://github.com/peterbarker/solodevguide/blob/njoubert-patch-1/book/concept-architecture.md

According to that information, modifying seiral2 should not affect the gimbal, so it appears that that information is incorrect.

Note that the gimbal speaks MAVLink.  It determines its pitch based on that.

**Pull request closed without merging**
