### PR TITLE
Prevent arming in a GPS flight mode if GPS is drifting

### PR DESCRIPTION
**Pull request by priseborough**
This patch extends the GPS checks applied to setting a GPS origin to the ready for GPS flight status reporting. It addresses https://3drsolo.atlassian.net/browse/FC-186.

### CODE REVIEW

**Comment by MAVProxyUser** [comment]
The Jira instance is private... can you open it to public view please? https://3drsolo.atlassian.net/browse/FC-186.

**Comment by Gussy** [comment]
Sorry Kevin, JIRA is for 3DR employees and contractors only at this point in time.

**Comment by jschall** [comment]
Looks good, just trying to think of edge cases. @priseborough what happens if GPS stops returning fixes? gpsGoodToAlign would stay true. I'll merge and make a 1.0.3 per Nick's request.

**Comment by jschall** [comment]
Merged, thanks.

**Pull request closed without merging**
