### PR TITLE
Reset EKF in-flight if numerical failure occurs

### PR DESCRIPTION
**Pull request by priseborough**
Would have prevented the flyaway in this report:

https://3drsolo.atlassian.net/browse/SOLO-445

### CODE REVIEW

**Comment by priseborough** [comment]
This has been bench tested by creating a patch that divided quaternion and height states by zero when the vehicle was shocked. The vehicle was armed and struck with motors running to cause the filter to fail. The filter reset successfully. This test was performed in loiter and stabilise modes without GPS.

Furter testing in SITL is required to determine the system response to the reset is acceptable in other flight modes.

**Comment by priseborough** [comment]
I've rebased on master and added changes in response to the peer review comments.

**Comment by jschall** [comment]
Rebased and made some changes to gyro3 bias estimate. Needs review today @priseborough @bugobliterator

**Comment by tcauchois** [comment]
Looks great to me!

**Comment by jschall** [comment]
merged

**Pull request closed without merging**
