### PR TITLE
refactor battery failsafe logic and don't RTL due to battery failsafe if currently LANDing

### PR DESCRIPTION
**Pull request by jschall**

### CODE REVIEW

**Comment by jschall** [comment]
@rmackay9 this could use a review.

**Comment by jschall** [comment]
or @priseborough

**Comment by rmackay9** [comment]
In master we've hard-coded the distance based RTL vs LAND decision to always use a distance of 5m.  I agree it doesn't get exercised much but I also don't see much point in changing it.  If you bring it up with the community they will propose a better solution (like the cone thing from Jason) rather than removing the distance completely.

The non-functional refactor looks good to me (although I haven't tested it).

As always, there is a counter argument to the "don't RTL due to battery failsafe if currently LANDing" which is that you don't know whether the vehicle is landing near home or not.  Technically you also don't know if the user is intending to let the copter get all the way to the ground.  I would run this behaviour through drones-discuss and/or bring it up on a dev call to see what people think.

**Comment by jschall** [comment]
The cone (from me, not Jason, if it matters) is already implemented on Solo. That is why I am removing this logic.

**Comment by rmackay9** [comment]
@jschall, ok, if the cone is coming too then it should be fine.

**Pull request closed without merging**
