### PR TITLE
Remote Logging

### PR DESCRIPTION
**Pull request by bugobliterator**
First piece of the remotely logging dataflash log inside sololink board then to artoo and finally to cloud database via solo app

### CODE REVIEW

**Comment by priseborough** [comment]
Helps for testing and provides baud rate change required to support gimbal dev.

**Comment by jschall** [comment]
Merged to solo-U1.1 branch.

**Comment by OXINARF** [comment]
I've been looking at this and I have a question: what happens if the Linux processor stops for some reason? Wouldn't logging just stop? Remote logging is an excellent idea but I think that local logging should be done at the same time.

**Comment by jschall** [comment]
@OXINARF Nope, one of the goals of this is to eliminate the SD card. Not much point of having 2 SD cards on board the vehicle.

**Comment by OXINARF** [comment]
I understand that, but what happens if the Linux processor halts? Then you would have no log from that point forward. It would make it easy for someone to halt the processor (and that's not hard at all) and then say that it had a crash even if it didn't.

**Pull request closed without merging**
