### PR TITLE
Position-based battery failsafe

### PR DESCRIPTION
**Pull request by wsilva32**
- Extended the position based failsafe math implemented earlier (but never before activated)
- Calculates rise, traversal, and descent distances for RTL based on the HOME and vehicle locations
- The resulting mAh required becomes an additional current failsafe penalty
- Lowered the baseline current failsafe back to 520mAh
- Assume that at worst case RTL, the vehicle will draw 26 amps
- Reduced RTL speed to 9 m/s to better accommodate the R10C payload

### CODE REVIEW

**Comment by wsilva32** [comment]
I'll flight test tomorrow and post comparison results.

**Comment by nick3dr** [comment]
Please don't merge this until we're ready for v4.2

**Comment by wsilva32** [comment]
@liamstask once flight tests have performed, we'll need to rebase prior to merge.

**Comment by liamstask** [comment]
👍

**Pull request merged**
