### PR TITLE
Prevent failure to use GPS due to change in magnetic field after startup

### PR DESCRIPTION
**Pull request by jschall**
Same as #153 but PRed on solo-U1.1 base.

>If we change the magnetic field environment after startup, the innovations in magnetic field states can cause the EKF to not pass the GPS checks due to uncertainty in heading.

>This patch checks for consistency in magnetometers and if they are consistent and innovation checks are failing for longer than 5 seconds, the magnetic field and yaw angle is reset which will enable the check to pass if the EKF solution is stable.

>It requires the compass consistency check methods introduced by https://github.com/3drobotics/ardupilot-solo/tree/solo-pr-mag-consistent

### CODE REVIEW

**Comment by priseborough** [comment]
OK, will modify naming and comments to make the intended function clearer

**Comment by jschall** [comment]
Thanks Paul. Going to assume that we don't want to disable this while the vehicle is armed. I'll pull this in to the release I'm making.

**Comment by jschall** [comment]
Fixed issues with my consistent() function, squashed the extraneous commits and force-pushed this one.

**Comment by bugobliterator** [comment]
Reviewed!

**Pull request closed without merging**
