### PR TITLE
Added moving average to SITL baro and magnetometer 

### PR DESCRIPTION
**Pull request by wsilva32**
and lowered reporting rate to 10Hz. Also removed an update of _last_update_usec in setHIL() since it was already being updated by publish_filtered_field(). This should help address some of the EKF SITL issues per FC-207. 

Ready for review @jschall and anyone else you feel might want to take a look.

### CODE REVIEW

**Comment by wsilva32** [comment]
Averaging on baro is causing altitude drift, closing until resolved.

**Comment by wsilva32** [comment]
Averaging (exponentially) over 1000 samples is too conservative. 100 samples seems to work much better. @jschall Do you know how many samples are kept in the average for the Solo HW?

**Comment by jschall** [comment]
Pixhawk samples the baro at ~100Hz and averages ~10 samples so that it
reports a new sample at 10Hz. You should try to do something very similar
in SITL.

On Mon, Sep 28, 2015 at 8:00 AM, Will Silva <notifications@github.com>
wrote:

> Averaging (exponentially) over 1000 samples is too conservative. 100
> samples seems to work much better. @jschall <https://github.com/jschall>
> Do you know how many samples are kept in the average for the Solo HW?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/3drobotics/ardupilot-solo/pull/181#issuecomment-143767863>
> .
>



-- 
Jonathan Challinger | Software Developer
3D Robotics Inc     | C: 530-864-8346

**Comment by wsilva32** [comment]
Alright, is it same for the mag (samples 100Hz and averages 10 samples to report at 10Hz?)

**Comment by jschall** [comment]
Yeah it is

**Comment by jschall** [comment]
Also in both cases the average is accumulated until read() is called and that is when a sample is reported.

**Pull request closed without merging**
