### PR TITLE
Copter: don't allow GCS mode changes during RC failsafe

### PR DESCRIPTION
**Pull request by jschall**

### CODE REVIEW

**Comment by OXINARF** [comment]
I think I understand the reasoning behind this but won't this prevent some 3dr party script in Solo to change mode after losing radio connection? Or that is something that 3DR won't support?

**Comment by jschall** [comment]
@OXINARF we'd need to handle the race conditions some other way, then. The answer to that is probably that we won't support that functionality, at least for now.

**Comment by OXINARF** [comment]
@jschall won't this just move the race condition here? I mean, failsafe will take time to be set, in that period a MAVLink message can arrive anyway. Also in that period Sololink already knows that RC link was lost, it is the first to know, right? Can't Sololink avoid the MAVLink messages if it detects RC link was lost?

Running scripts with mode changing was one of the things that interested me in Solo, that's why I'm so "against" this.

**Comment by nick3dr** [comment]
Scripts on sololink could (should?) continue to send RC packets to the
pixhawk like a smartshot does

On Mon, Oct 19, 2015 at 5:08 PM, Francisco Ferreira <
notifications@github.com> wrote:

> @jschall <https://github.com/jschall> won't this just move the race
> condition here? I mean, failsafe will take time to be set, in that period a
> MAVLink message can arrive anyway. Also in that period Sololink already
> knows that RC link was lost, it is the first to know, right? Can't Sololink
> avoid the MAVLink messages if it detects RC link was lost?
>
> Running scripts with mode changing was one of the things that interested
> me in Solo, that's why I'm so "against" this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/3drobotics/ardupilot-solo/pull/190#issuecomment-149381708>
> .
>



-- 
◤*NICK SPEAL*
    engineering project manager
    3D Robotics
    415.599.1404
    website <http://www.3dr.com/> | facebook
<http://www.facebook.com/3drobotics> | Instagram
<http://www.instagram.com/3drobotics>

**Comment by jschall** [comment]
@OXINARF the suggestion from @rmackay9 is to use the GCS failsafe functionality to trigger another failsafe once the GCS is lost. However, upstream does agree that radio failsafe should prevent modes that depend on radio input from being selected.

**Comment by OXINARF** [comment]
@jschall @rmackay9 is correct, even for the functionality I was thinking I would have to disable radio failsafe and use the GCS one, so this wouldn't affect it.

> However, upstream does agree that radio failsafe should prevent modes that depend on radio input from being selected

Does this mean that modes like Auto, Land, Guided or RTL shouldn't be disabled even in case of radio failsafe? I'm thinking for example if you have radio failsafe to continue during a mission and you lose radio connection but still have telemetry working: why not being able to tell it to land or use Guided to tell it to go another place, etc?

**Comment by jschall** [comment]
After investigating alternatives it appears that this is the way to go.

**Pull request closed without merging**
